export const CREATE_PATIENT = "CREATE_PATIENT";
export const CREATE_CHART = "CREATE_CHART";
export const LOAD_PATIENTS_SUCCESS = "LOAD_PATIENTS_SUCCESS";
export const LOAD_CHARTS_SUCCESS = "LOAD_CHARTS_SUCCESS";
export const CREATE_CHART_SUCCESS = "CREATE_CHART_SUCCESS";
export const UPDATE_CHART_SUCCESS = "UPDATE_CHART_SUCCESS";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS"

